// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-S9kqvrxvXO8ne2QNB6_ZJdNfPTfdOMA',
    appId: '1:704377877325:web:4b8125d939509313bdbd04',
    messagingSenderId: '704377877325',
    projectId: 'foodplanner-e5cdd',
    authDomain: 'foodplanner-e5cdd.firebaseapp.com',
    storageBucket: 'foodplanner-e5cdd.appspot.com',
    measurementId: 'G-MMR86R7Y7M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpYkiE5k_NTXzwrc0KSCaXV9fLPYTRPHQ',
    appId: '1:704377877325:android:4abb2fda57add4a2bdbd04',
    messagingSenderId: '704377877325',
    projectId: 'foodplanner-e5cdd',
    storageBucket: 'foodplanner-e5cdd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCZtkYXCb2CUlX93CRVUZ05Wr2yQXF08E',
    appId: '1:704377877325:ios:8a1dbb85689539e6bdbd04',
    messagingSenderId: '704377877325',
    projectId: 'foodplanner-e5cdd',
    storageBucket: 'foodplanner-e5cdd.appspot.com',
    androidClientId: '704377877325-5o5fthn2f3tdb7tgdhjdkr5hbbsuahng.apps.googleusercontent.com',
    iosClientId: '704377877325-tphav4ar0sr8af4esui8tm44oakv5a96.apps.googleusercontent.com',
    iosBundleId: 'bundle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCZtkYXCb2CUlX93CRVUZ05Wr2yQXF08E',
    appId: '1:704377877325:ios:592ee46604e57c7fbdbd04',
    messagingSenderId: '704377877325',
    projectId: 'foodplanner-e5cdd',
    storageBucket: 'foodplanner-e5cdd.appspot.com',
    androidClientId: '704377877325-5o5fthn2f3tdb7tgdhjdkr5hbbsuahng.apps.googleusercontent.com',
    iosClientId: '704377877325-isdavg54eip94eneann5iigogg39vtfn.apps.googleusercontent.com',
    iosBundleId: 'mfp',
  );
}
